name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-experimental-swift-testing --disable-xctest --enable-code-coverage
    - name: Prepare coverage file
      run: xcrun llvm-cov export -format="lcov" .build/debug/swift-environment-decoderPackageTests.xctest/Contents/MacOS/swift-environment-decoderPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
        verbose: true
  build-swift-5-10:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Check Swift version
      run: swift --version
    - name: Build
      run: swift build
