name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: irgaly/setup-mint@v1
    - name: SwiftLint
      run: mint run swiftlint --strict
  SwiftFormat:
    runs-on: macos-latest
    needs: SwiftLint
    steps:
    - uses: actions/checkout@v4
    - uses: irgaly/setup-mint@v1
    - name: SwiftFormat Lint
      run: mint run swiftformat --lint .
  Docc:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v4
    - name: Swift-Docc Validate
      run: swift package generate-documentation --analyze --warnings-as-errors
